export const INCREASE = "INCREASE"

export const FETCH_POLLS = "FETCH_POLLS"
export const CANCEL_FETCH_POLLS = "CANCEL_FETCH_POLLS"
export const FETCH_POLLS_SUCCESS = "FETCH_POLLS_SUCCESS"
export const FETCH_POLLS_FAILED = "FETCH_POLLS_FAILED"